LibraryManagementMVC/LibraryManagement.MvcWebUI/Models/BookViewModel.cs
using LibraryManagement.Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LibraryManagement.MvcWebUI.Models
{
    public class BookViewModel
    {
        public List<Book> Books { get; internal set; }
    }
}

LibraryManagementMVC/LibraryManagement.MvcWebUI/Models/MemberViewModel.cs
using LibraryManagement.Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LibraryManagement.MvcWebUI.Models
{
    public class MemberViewModel
    {
        public List<Member>  Members { get; internal set; }

    }
}

LibraryManagementMVC/LibraryManagement.MvcWebUI/Controllers/BooksController.cs
using LibraryManagement.Business.Abstract;
using LibraryManagement.Business.Concrete;
using LibraryManagement.DataAccess.Concrete.EntityFramework;
using LibraryManagement.Entities.Concrete;
using LibraryManagement.MvcWebUI.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryManagement.MvcWebUI.Controllers
{
    public class BooksController : Controller
    {
        // GET: Book

        private IBookService _bookService;

        public BooksController(IBookService bookService)
        {
            _bookService = bookService;
        }

        public ActionResult Index()
        {
            List<Book> book = _bookService.GetAll();
            return View(book);

        }

        public ActionResult GetDetails(int id)
        {
            var book = _bookService.GetById(id);
            return View(book);
        }

        [HttpPost]
        public ActionResult GetDetails(int id, Book book)
        {
            if (ModelState.IsValid)
            {
                _bookService.GetById(id);
                return RedirectToAction("Index");
            }
            return View(book);
        }

        public ActionResult CreateNew()
        {
            return View(new Book());
        }

        [HttpPost]
        public ActionResult CreateNew(Book book)
        {
            if (ModelState.IsValid)
            {
                _bookService.Add(book);
                return RedirectToAction("Index");
            }

            return View(book);
        }

        public ActionResult EditBook(int id)
        {
            Book book = _bookService.GetById(id);
            return View(book);
        }

        [HttpPost]
        public ActionResult EditBook(Book book)
        {
            if (ModelState.IsValid)
            {
                _bookService.Update(book);
                return RedirectToAction("Index");
            }
            return View(book);
        }

    }
}

LibraryManagementMVC/LibraryManagement.MvcWebUI/Controllers/LendBooksController.cs
using LibraryManagement.Business.Abstract;
using LibraryManagement.Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryManagement.MvcWebUI.Controllers
{
    public class LendBooksController : Controller
    {
        // GET: LendBook
        private IBookService _bookService;

        public LendBooksController(IBookService bookService)
        {
            _bookService = bookService;
        }

        public RedirectToRouteResult AddBookToLendList(int id)
        {
            Book book = _bookService.GetById(id);
            var bookcart = (BooksLend)Session["bookcart"];

            if (bookcart == null)
            {
                bookcart = new BooksLend();
                Session["bookcart"] = bookcart;
            }
            bookcart.LendBook(book, 1);
            return RedirectToAction("LendBook", bookcart);
        }
        public ViewResult LendBook()
        {
            var bookcart = (BooksLend)Session["bookcart"];
            return View(bookcart);
        }

        public RedirectToRouteResult RemoveBookFromLendList(int id)
        {
            Book book = _bookService.GetById(id);
            var bookcart = (BooksLend)Session["bookcart"];

            bookcart.RemoveLendBook(book);
            return RedirectToAction("LendBook", bookcart);
        }
        //public ViewResult LendBook()
        //{
        //    var bookcart = (BooksLend)Session["bookcart"];
        //    return View(bookcart);
        //}


        //if (bookcart.Lines.Count==0)
        //{
        //    ModelState.AddModelError("","Listede Kitap yok !");
        //}
        //else
        //{
        //    bookcart.RemoveLendBook(book);

        //}



    }
}

LibraryManagementMVC/LibraryManagement.MvcWebUI/Controllers/MembersController.cs
using LibraryManagement.Business.Abstract;
using LibraryManagement.Entities.Concrete;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryManagement.MvcWebUI.Controllers
{
    public class MembersController : Controller
    {
        // GET: Members

        private IMemberService _memberService;

        public MembersController(IMemberService memberService)
        {
            _memberService = memberService;
        }

        public ActionResult MemberList()
        {
            return View(_memberService.GetAll().ToList());
        }

        public ActionResult CreateNewMember()
        {
            return View(new Member());
        }

        [HttpPost]
        public ActionResult CreateNewMember(HttpPostedFileBase file, Member member)
        {
            string fileName = Path.GetFileName(file.FileName);
            string _fileName = DateTime.Now.ToString("yymmssfff") + fileName;
            string extension = Path.GetExtension(file.FileName);
            string path = Path.Combine(Server.MapPath("~/Images/member_images/"), _fileName);

            member.ImagePath = "~/Images/member_images/" + _fileName;

            if (extension.ToLower() == ".jpg" || extension.ToLower() == ".jpeg" || extension.ToLower() == ".png")
            {
                if (file.ContentLength <= 1000000)
                {
                    _memberService.Add(member);
                    file.SaveAs(path);
                    return RedirectToAction("MemberList");
                }
            }

            return View(member);
        }

        public ActionResult MemberDetails(int id)
        {
            var member = _memberService.GetById(id);
            return View(member);
        }

        [HttpPost]
        public ActionResult MemberDetails(int id, Member member)
        {
            if (ModelState.IsValid)
            {
                _memberService.GetById(id);
                return RedirectToAction("Index");
            }
            return View(member);
        }

    }
}



//public ActionResult AddNewMember(Member member)
//{
//    if (ModelState.IsValid)
//    {
//        _memberService.Add(member);
//        return RedirectToAction("Index");
//    }

//    return View(member);
//}


//public ActionResult FileUpload(Member member, HttpPostedFileBase file)
//{
//    if (ModelState.IsValid)
//    {
//        if (file != null)
//        {
//            file.SaveAs(HttpContext.Server.MapPath("~/Images/")
//                                                  + file.FileName.LastIndexOf("."));
//            member.ImagePath = file.FileName;
//        }
//        _memberService.Add(member);
//        return RedirectToAction("AddNewMember", "Members");
//    }
//    return View(member);
//}

LibraryManagementMVC/LibraryManagement.MvcWebUI/Views/Books/CreateNew.cshtml
@model  LibraryManagement.Entities.Concrete.Book
@using LibraryManagement.MvcWebUI.HtmlHelpers

@{
    ViewBag.Title = "CreateNew";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <form>
        <div class="form-group" style="border-style: solid; border-color: #937341; border-width:1.75px;padding:10px">
            <div class="form-group">
                <label for="newBookName">Kitap Adı</label>
                @Html.EditorFor(model => model.BookName, new { htmlAttributes = new { @class = "form-control", id = "newBookName", placeholder = "Eklemek kitap adını giriniz" } })
            </div>
            <div class="row">
                <div class="form-group col-md-4">
                    <label for="newAuthorId">Yazar ID</label>
                    @Html.TextBoxFor(model => model.AuthorId, htmlAttributes: new { @class = "form-control", id = "newAuthorId" })
                </div>
                <div class="form-group col-md-4">
                    <label for="newAuthorName">Yazar Adı</label>
                    @Html.EditorFor(model => model.AuthorName, new { htmlAttributes = new { @class = "form-control", id = "newAuthorName", placeholder = "Eklemek istediğiniz yazar ismini giriniz" } })
                </div>
                <div class="form-group col-md-4">
                    <label for="newType">Tür</label>
                    @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control", id = "newType", placeholder = "Tür" } })
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-4">
                    <label for="newPublisherName">Yayınevi</label>
                    @Html.EditorFor(model => model.PublisherName, new { htmlAttributes = new { @class = "form-control", id = "newPublisherName", placeholder = "Yayınevi adını giriniz" } })
                </div>
                <div class="form-group col-md-4">
                    <label for="newPublishDate">Yayınlanma Tarihi</label>
                    @Html.EditorFor(model => model.PublishDate, new { htmlAttributes = new { @class = "form-control", id = "newPublishDate", @type = "date" } })
                </div>
                <div class="form-group col-md-4">
                    <label for="newLanguage">Dil</label>
                    @Html.EditorFor(model => model.Language, new { htmlAttributes = new { @class = "form-control", id = "newLanguage", placeholder = "Dil" } })
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-3">
                    <label for="newEdition">Baskı</label>
                    @Html.EditorFor(model => model.Edition, new { htmlAttributes = new { @class = "form-control", id = "newEdition", placeholder = "Baskı" } })
                </div>
                <div class="form-group col-md-3">
                    <label for="newBookCost">Fiyat</label>
                    @Html.EditorFor(model => model.BookCost, new { htmlAttributes = new { @class = "form-control", id = "newBookCost" } })
                </div>
                <div class="form-group col-md-3">
                    <label for="newPageNumber">Sayfa Sayısı</label>
                    @Html.EditorFor(model => model.PageNumber, new { htmlAttributes = new { @class = "form-control", id = "newPageNumber", placeholder = "Sayfa sayısını giriniz" } })
                </div>
                <div class="form-group col-md-3">
                    <label for="newQuantity">Stok Adedi</label>
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control", id = "newQuantity" } })
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label for="newInStock">Stok Durumu(Evet/Hayır)</label>
                    @Html.CheckBoxFor(model => model.InStock, htmlAttributes: new { @class = "form-controller", style = "height:20px;width:20px;margin-left:5px;", id = "newInStock" })
                </div>
            </div>
            <div class="form-group">
                <label for="newBookDescription">Kitap Özeti</label>
                @Html.TextAreaFor(model => model.BookDescription, htmlAttributes: new { style = "height:270px;resize:none", @class = "form-control", id = "newBookDescription" })
            </div>
            <br />
            <div><button type="submit" class="btn btn-success" id="btnAdd" style="width:280px" onclick="location.href = '@Url.Action("CreateNew","Books")'">Kitabı Kaydet</button></div>
            <a href='@Url.Action("Index","Books")' class="btn btn-default" style="width:280px; text-align:center; border-style:solid; border-color:#937341; border-width:0.5px;margin-top:3px" title="Listeye geri dön">
                Listeye Geri Dön
                <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
            </a>
        </div>
    </form>
}



<!--<form>
    <div class="form-group" style="border-style: solid; border-color: #937341; border-width:1.75px;padding:10px">
        <div class="form-group">
            <label for="newBookName">Kitap Adı</label>
            @*<input type="text" class="form-control" id="newBookName" placeholder="Eklemek kitap adını giriniz" @Html.TextBoxFor(model => model.BookName) />*@
        <!--</div>
        <div class="row">
            <div class="form-group col-md-4">
                <label for="newAuthorId">Yazar ID</label>
                @*<input type="text" class="form-control" id="newAuthorId" placeholder="Yazar Id giriniz" @Html.TextBoxFor(model => model.AuthorId) />*@
            <!--</div>
            <div class="form-group col-md-4">
                <label for="newAuthorName">Yazar Adı</label>
                @*<input type="text" class="form-control" id="newAuthorName" placeholder="Eklemek istediğiniz yazar ismini giriniz" @Html.TextBoxFor(model => model.AuthorName) />*@
            <!--</div>
            <div class="form-group col-md-4">
                <label for="newType">Tür</label>
                <input type="text" class="form-control" id="newType" placeholder="Tür" @Html.TextBoxFor(model => model.Type) />
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-4">
                <label for="newPublisherName">Yayınevi</label>
                <input type="text" class="form-control" id="newPublisherName" placeholder="Yayınevi adını giriniz" @Html.TextBoxFor(model => model.PublisherName) />
            </div>
            <div class="form-group col-md-4">
                <label for="newPublishDate">Yayınlanma Tarihi</label>
                <input type="date" class="form-control" id="newPublishDate" style="background-color:lightgrey" @Model.PublishDate />
            </div>
            <div class="form-group col-md-4">
                <label for="newLanguage">Dil</label>
                <input type="text" class="form-control" id="newLanguage" placeholder="Dil" @Model.Language />
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-3">
                <label for="newEdition">Baskı</label>
                <input type="text" class="form-control" id="newEdition" @Model.Edition />
            </div>
            <div class="form-group col-md-3">
                <label for="newBookCost">Fiyat</label>
                <input type="text" class="form-control" id="newBookCost" placeholder="Satış ücretini giriniz" @Model.BookCost />
            </div>
            <div class="form-group col-md-3">
                <label for="newPageNumber">Sayfa Sayısı</label>
                <input type="text" class="form-control" id="newPageNumber" placeholder="Sayfa sayısını giriniz" @Model.PageNumber />
            </div>
            <div class="form-group col-md-3">
                <label for="newQuantity">Stok Adedi</label>
                <input type="text" class="form-control" id="newQuantity" placeholder="Satış ücretini giriniz" @Model.Quantity />
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-6">
                <label for="newInStock" class="container-fluid">Stok Durumu(Evet/Hayır)</label>
                <input type="checkbox" class="checkbox-inline" id="newInStock" style="height:30px;width:30px" @Html.YesNo(@Model.InStock) />
            </div>
        </div>
        <div class="form-group">
            <label for="newBookDescription">Kitap Özeti</label>
            <textarea class="form-control" id="newBookDescription" style="height:270px;resize:none" @Model.BookDescription></textarea>
        </div>
        <br />
        <div><button type="submit" class="btn btn-success" id="btnAdd" style="width:280px" onclick="location.href = '@Url.Action("CreateNew","Books")'">Kitabı Kaydet</button></div>
        <a href='@Url.Action("Index","Books")' class="btn btn-default" style="width:280px; text-align:center; border-style:solid; border-color:#937341; border-width:0.5px" title="Listeye geri dön">
            Listeye Geri Dön
            <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
        </a>
    </div>
</form>-->

LibraryManagementMVC/LibraryManagement.MvcWebUI/Views/Books/DeleteBook.cshtml
@model LibraryManagement.Entities.Concrete.Book

@{
    ViewBag.Title = "DeleteBook";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container" style="display:inline-flex;margin-bottom:10px">
    <div class="row" style="display:inline-flex">
        <div class="column">
            <h2 style="color:orange; padding:3px">Kitabı Sil</h2>
        </div>
        <div class="column">
            <img src="~/Images/icons/delete-icon.png" class="img-responsive" style="position:center; padding:12px" />
        </div>
    </div>
</div>


@using (Html.BeginForm())
{

    @Html.AntiForgeryToken()
    <form>
        <div class="form-group" style="border-style: solid; border-color: #937341; border-width:1.75px;padding:10px; border-radius:25px">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.BookId)

            <div class="form-group">
                <label for="deleteBookName">Kitap Adı</label>
                @Html.EditorFor(model => model.BookName, new { htmlAttributes = new { @class = "form-control", id = "deleteBookName", disabled = "" } })
            </div>
            <div class="row">
                <div class="form-group col-md-4">
                    <label for="deleteAuthorId">Yazar ID</label>
                    @Html.TextBoxFor(model => model.AuthorId, htmlAttributes: new { @class = "form-control", id = "deleteAuthorId", disabled = "" })
                </div>
                <div class="form-group col-md-4">
                    <label for="deleteAuthorName">Yazar Adı</label>
                    @Html.EditorFor(model => model.AuthorName, new { htmlAttributes = new { @class = "form-control", id = "deleteAuthorName", disabled = "" } })
                </div>
                <div class="form-group col-md-4">
                    <label for="deleteType">Tür</label>
                    @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control", id = "deleteType", disabled = "" } })
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-4">
                    <label for="deletePublisherName">Yayınevi</label>
                    @Html.EditorFor(model => model.PublisherName, new { htmlAttributes = new { @class = "form-control", id = "deletePublisherName", disabled = "" } })
                </div>
                <div class="form-group col-md-4">
                    <label for="deletePublishDate">Yayınlanma Tarihi</label>
                    @Html.EditorFor(model => model.PublishDate, new { htmlAttributes = new { @class = "form-control", id = "deletePublishDate", disabled = "" } })
                </div>
                <div class="form-group col-md-4">
                    <label for="deleteLanguage">Dil</label>
                    @Html.EditorFor(model => model.Language, new { htmlAttributes = new { @class = "form-control", id = "deleteLanguage", disabled = "" } })
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-3">
                    <label for="deleteEdition">Baskı</label>
                    @Html.EditorFor(model => model.Edition, new { htmlAttributes = new { @class = "form-control", id = "deleteEdition", disabled = "" } })
                </div>
                <div class="form-group col-md-3">
                    <label for="deleteBookCost">Fiyat</label>
                    @Html.EditorFor(model => model.BookCost, new { htmlAttributes = new { @class = "form-control", id = "deleteBookCost", disabled = "" } })
                </div>
                <div class="form-group col-md-3">
                    <label for="deletePageNumber">Sayfa Sayısı</label>
                    @Html.EditorFor(model => model.PageNumber, new { htmlAttributes = new { @class = "form-control", id = "deletePageNumber", disabled = "" } })
                </div>
                <div class="form-group col-md-3">
                    <label for="deleteQuantity">Stok Adedi</label>
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control", id = "deleteQuantity", disabled = "" } })
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-6">
                    <label for="deleteInStock">Stok Durumu(Evet/Hayır)</label>
                    @Html.CheckBoxFor(model => model.InStock, htmlAttributes: new { @class = "form-controller", style = "height:20px;width:20px;margin-left:5px;", id = "deleteInStock", disabled = "" })
                </div>
            </div>

            <div class="form-group">
                <label for="deletetBookDescription">Kitap Özeti</label>
                @Html.TextAreaFor(model => model.BookDescription, htmlAttributes: new { style = "height:270px;resize:none", @class = "form-control", id = "deleteBookDescription", disabled = "" })
            </div>
            <br />
            <div class="row">
                <div class="form-group col-md-3">
                    <div><button type="submit" class="btn btn-danger" id="btnDelete" style="width:100%" onclick="location.href = '@Url.Action("DeleteBook","Books")'">Kitabı Sil</button></div>
                    <a href='@Url.Action("Index","Books")' class="btn btn-default" style="width:100%; text-align:center; border-style:solid; border-color:#937341; border-width:0.5px;margin-top:10px" title="Listeye geri dön">
                        Listeye Geri Dön
                        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
                    </a>
                </div>
            </div>
            @*<div><button type="submit" class="btn btn-danger" id="btnDelete" style="width:280px" onclick="location.href = '@Url.Action("DeleteBook", "Books")'">Kitabı Sil</button></div>
            <a href='@Url.Action("Index", "Books")' class="btn btn-default" style="width:280px; text-align:center; border-style:solid; border-color:#937341; border-width:0.5px;margin-top:10px" title="Listeye geri dön">
                Listeye Geri Dön
                <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
            </a>
        </div>*@

    </form>
}

LibraryManagementMVC/LibraryManagement.MvcWebUI/Views/Books/GetDetails.cshtml
@model LibraryManagement.Entities.Concrete.Book
@using LibraryManagement.MvcWebUI.HtmlHelpers
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm())

{
    @Html.AntiForgeryToken()

    <div class="container" style="margin-top:10px">
        <div class="row">
            <div class="col-md-4">
                <label for="bookName">Kitap Adı:</label>
                <h4>@Model.BookName</h4>
            </div>

            <div class="col-md-8" style="border-style: solid; border-color: #937341; border-width:1.75px;padding:10px">

                <div class="form-group">
                    <label for="bookName">Kitap Adı</label>
                    <div class="form-control" id="bookName">@Model.BookName</div>
                </div>
                <div class="form-group">
                    <label for="authorName">Yazar Adı</label>
                    <div class="form-control" id="authorName">@Model.AuthorName</div>
                </div>
                <div class="form-group">
                    <label for="publisherName">Yayınevi Adı</label>
                    <div class="form-control" id="publisherName">@Model.PublisherName</div>
                </div>
                <div class="row">
                    <div class="form-group col-md-4">
                        <label for="publisDate">Yayınlanma Tarihi</label>
                        <div class="form-control" id="publisDate">@Model.PublishDate.Date.ToShortDateString()</div>
                    </div>
                    <div class="form-group col-md-4">
                        <label for="language">Dil</label>
                        <div class="form-control" id="language">@Model.Language</div>
                    </div>
                    <div class="form-group col-md-4">
                        <label for="quantity">Stok Adedi</label>
                        <div class="form-control" id="quantity">@Model.Quantity</div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-3">
                        <label for="edition">Baskı</label>
                        <div class="form-control" id="edition">@Model.Edition</div>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="bookCost">Fiyat</label>
                        <div class="form-control" id="bookCost">@Model.BookCost</div>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="pageNumber">Sayfa Sayısı</label>
                        <div class="form-control" id="pageNumber">@Model.PageNumber</div>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="inStock">Stok Durumu</label>
                        <div class="form-control" id="inStock">@Html.YesNo(@Model.InStock)</div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="bookDescription">Kitap Özeti</label>
                    <div class="form-control" id="bookDescription" style="height:270px">@Model.BookDescription</div>
                </div>
                <br />
                <a href='@Url.Action("Index","Books")' class="btn btn-default" style="width:280px; text-align:center; border-style:solid; border-color:#937341; border-width:0.5px" title="Listeye geri dön">
                    Listeye Geri Dön
                    <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
                </a>
            </div>
        </div>
    </div>
}


@*<div class="container-md" style="border-style: solid; border-color: #937341; border-width: 2px; padding:5px;margin:5px">

        <div class="form-group">
            <label for="bookName">Kitap Adı</label>
            @Html.EditorFor(model => model.BookName, new { htmlAttributes = new { @class = "form-control", type = "text", id = "bookName" } })
        </div>
        <div class="form-group">
            <div><h4>Görev Açıklaması</h4></div>
            @Html.EditorFor(model => model.AuthorName, new { htmlAttributes = new { @class = "form-control" } })
        </div>
        <div class="form-group">
            @Html.CheckBoxFor(model => model.InStock, new { htmlAttributes = new { @class = "form-control" } })
            Stokta Var mı ?
        </div>
        <div class="form-group">
            <div><h4>Görevin Oluşturulma Zamanı</h4></div>
            @Html.EditorFor(model => model.PublisherName, new { htmlAttributes = new { @class = "form-control" } })
        </div>
        <div class="form-group">
            <div><h4>Görevin Yapılması Gereken Tarih</h4></div>
            <textarea style="width: 280px; height:100px">@Model.BookDescription</textarea>
        </div>
        <div>
            <br />
            <a href='@Url.Action("Index","Books")' class="btn btn-default" style="width:280px; text-align:center; border-style:solid; border-color:#937341; border-width:2px" title="Listeye geri dön">
                Listeye Geri Dön
                <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
            </a>
        </div>
    </div>*@

LibraryManagementMVC/LibraryManagement.MvcWebUI/Views/LendBooks/LendBook.cshtml
@model LibraryManagement.Entities.Concrete.BooksLend
@{
    ViewBag.Title = "LendBook";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Kitap Ödünç Ver</h2>

<table id="lendList" class="table table-bordered table-responsive table-hover" width="100%">
    <thead class="thead-dark">
        <tr style="border-style:solid;border-width:1px">
            <th class="th-sm" style="border-width:1px">
                Kitap Adı
            </th>
            <th class="th-sm" style="border-width:1px">
                Yazar Adı
            </th>
            <th class="th-sm" style="border-width:1px">
                Kitabı Alan Kişi(Ad-Soyad)
            </th>
            <th class="th-sm" style="border-width:1px">
                Miktar(Adet)
            </th>
            <th class="th-sm" style="border-width:1px; color:red; text-align:center">
                İşlem
            </th>
        </tr>
    </thead>
    @foreach (var line in Model.Lines)
    {

        <tr>
            <td>@line.Book.BookName</td>
            <td>@line.Book.AuthorName</td>
            <td>Girilmemiş</td>
            <td>@line.Quantity</td>
            @using (Html.BeginForm("RemoveBookFromLendList", "LendBooks"))
            {
                @Html.Hidden("id", line.Book.BookId)
                @*<td><input type="submit" value="Listeden Çıkar" /></td>*@
                <td><button type="submit" class="btn btn-danger">Listeden Çıkar</button></td>

            }
        </tr>

    }
</table>
<div>
    <a href="@Url.Action("Index", "Books")" class="btn btn-success" style="width:180px">Listeye Geri Dön</a>
</div>

LibraryManagementMVC/LibraryManagement.MvcWebUI/Views/Members/MemberList.cshtml
@model IEnumerable<LibraryManagement.Entities.Concrete.Member>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.ImagePath)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.BirthDate)
        </th>
        <th class="th-sm" style="border-width:1px; color:red; text-align:center">
            İşlem
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.FirstName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.LastName)
    </td>
    @*<td>
            <img src="@Url.Content(item.ImagePath)" alt="Not Found" width="50" height="50" />
        </td>*@
    <td>
        @Html.DisplayFor(modelItem => item.BirthDate)
    </td>
    <td><center><a href="@Url.Action("MemberDetails", "Members", new { id = item.MemberId})" class="btn btn-info" style="padding:2px">Üye Detayı</a></center></td>

</tr>
}

</table>